### ISSUE TITLE
multiple authors seperated by , should be supported

### ISSUE THREAD

**Issue by harvimt** [orsinium/poetry-setup#8]

**Comment by harvimt** [comment]
I wrote this code to automatically grab the author email from `__AUTHOR__` in my `__init__.py`

```
groups = re.findall(r'(.+?) <(.+?)>(?:,\s*)?', quamash.__author__)
authors = [x[0].strip() for x in groups]
emails = [x[1].strip() for x in groups]
```

**Comment by orsinium** [comment]
1. Poetry-setup for pyproject.toml. Why are you taking about `__init__.py`?
2. Poetry-setup is deprecated, as stayed in the readme. Please, use dephell instead. I haven't archived poetry-setup, because I ready to fix bugs. However, this issue more about feature.

**Comment by harvimt** [comment]
that was my old solution. to not having to repeat myself (you'll see it in a lot of old projects).

`__init__.py` contains `__author__`, `__version__` etc, then you import it in setup.py.

it's... not a good solution, which is part of why I'm moving to poetry.

but the regex will convert `"Author1 <email@isp>, Author2 <email2.isp>"` to the correct format for setup.py

**Comment by harvimt** [comment]
You're still the top hit for "poetry generate setup.py" dephell doesn't even show up in the first page of results for that, but I suppose you have no control over that (and archiving won't help, a lot of ancient projects show up at the top of search results)

**Comment by orsinium** [comment]
## About this issue

You can specify multiple authors in poetry config:

```toml
authors = ["Author1 <email@isp>", "Author2 <email2.isp>"]
```

Only first author will be used in setup.py, because setup.py doesn't support more than one author. Poetry also has the same behavior.

## About features

1. If you just discovered this project, please, use [dephell](https://github.com/dephell/dephell) as recommend in the readme for poetry-setup.
1. If your project depends on poetry-setup -- please, migrate on dephell.
1. If you can't migrate and found bug -- feel free to open an issue.
1. If you can't migrate and want a feature -- fork, do it and make PR. I always ready to review and accept Pull Requests.
1. If your company can't migrate, wants a feature and have no free developers for it -- your company can pay to me, and I will make any features that it wants.

I support all my projects, of course. Also, I ready to make features for my old projects, when it's important. However, poetry-setup has no value, because [dephell](https://github.com/dephell/dephell) all things that poetry-setup can and much more. Feel free to open any issues in dephell if you feel lack of some features.
